replicaCount: 2

image:
  repository: akshat120210/query
  pullPolicy: IfNotPresent
  tag: v2

service:
  type: ClusterIP
  port: 4002
  targetPort: 4002

config:
  eventBusUrl: "http://event-bus-production:4005"
  nodeEnv: production

secret:
  appSecret: change-me

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
