apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "event-bus.fullname" . }}-config
  labels:
    {{- include "event-bus.labels" . | nindent 4 }}

data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  POSTS_URL: {{ .Values.config.postsUrl | quote }}
  COMMENTS_URL: {{ .Values.config.commentsUrl | quote }}
  QUERY_URL: {{ .Values.config.queryUrl | quote }}
  MODERATION_URL: {{ .Values.config.moderationUrl | quote }}
