apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-bus.fullname" . }}-secret
  labels:
    {{- include "event-bus.labels" . | nindent 4 }}

type: Opaque

stringData:
  APP_SECRET: {{ .Values.secret.appSecret | quote }}
