apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "query.fullname" . }}
  labels:
    {{- include "query.labels" . | nindent 4 }}

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "query.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "query.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: query
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "query.fullname" . }}-config

            - secretRef:
                name: {{ include "query.fullname" . }}-secret

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
