apiVersion: v1
kind: Secret
metadata:
  name: {{ include "query.fullname" . }}-secret
  labels:
    {{- include "query.labels" . | nindent 4 }}

type: Opaque

stringData:
  APP_SECRET: {{ .Values.secret.appSecret | quote }}
