replicaCount: 2

image:
  repository: akshat120210/posts
  pullPolicy: IfNotPresent
  tag: v2

config:
  NODE_ENV: production

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
