replicaCount: 2

image:
  repository: akshat120210/event-bus
  pullPolicy: IfNotPresent
  tag: v2

service:
  type: ClusterIP
  port: 4005
  targetPort: 4005

config:
  nodeEnv: staging

secret:
  appSecret: change-me

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

