replicaCount: 2

image:
  repository: akshat120210/event-bus
  pullPolicy: IfNotPresent
  tag: v2

service:
  type: ClusterIP
  port: 4005
  targetPort: 4005

config:
  postsUrl: "http://posts-staging:4000"
  commentsUrl: "http://comments-staging:4001"
  queryUrl: "http://query-staging:4002"
  moderationUrl: "http://moderation-staging:4003"
  nodeEnv: staging

secret:
  appSecret: change-me

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

