replicaCount: 2

image:
  repository: akshat120210/event-bus
  pullPolicy: IfNotPresent
  tag: v2

service:
  type: ClusterIP
  port: 4005
  targetPort: 4005

config:
  nodeEnv: production

secret:
  appSecret: change-me

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
