replicaCount: 2

image:
  repository: akshat120210/comments
  pullPolicy: IfNotPresent
  tag: v2

service:
  type: ClusterIP
  port: 4001
  targetPort: 4001

config:
  NODE_ENV: staging

secret:
  APP_SECRET: change-me

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
