apiVersion: v1
kind: Secret
metadata:
  name: {{ include "posts.fullname" . }}-secret
  labels:
    {{- include "posts.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secret.APP_SECRET | quote }}
