apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moderation.fullname" . }}-config
  labels:
    {{- include "moderation.labels" . | nindent 4 }}

data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
