replicaCount: 2

image:
  repository: akshat120210/moderation
  pullPolicy: IfNotPresent
  tag: v2

service:
  type: ClusterIP
  port: 4003
  targetPort: 4003

config:
  eventBusUrl: "http://event-bus-staging:4005"
  nodeEnv: staging

secret:
  appSecret: change-me

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
