apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comments.fullname" . }}-secret
  labels:
    {{- include "comments.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secret.APP_SECRET | quote }}
