replicaCount: 3

image:
  repository: akshat120210/client
  pullPolicy: IfNotPresent
  tag: v1

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: client.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false
  parentRefs: []
  hostnames: []
  rules: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
